name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Please ensure the PR is still relevant. If not, please close the PR.'
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'
          days-before-stale: 60
          days-before-close: 30
          days-before-pr-close: -1
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'question,bug,documentation,enhancement,good first issue,help wanted'
