x-common-config:
  &common-config
  network_mode: host
  ipc: host

services:
  quadruped_robot:
    image: delicjusz/quadruped-robot:traj 
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    <<: *common-config
    # Realtime hardware (https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html#determinism)
    privileged: true
    ulimits:
      rtprio:
        soft: 99
        hard: 99
      memlock:
        soft: 102400
        hard: 102400
    volumes:
      - ../:/ros2_ws/src/
      - ./config:/config/cyclonedds.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///config/cyclonedds.xml
    command: >
      ros2 launch quadruped_robot_description joint_trajectory.launch.py
        use_hardware:=True