controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

effort_controllers:
  ros__parameters:
      joints:
        - front_left_first_joint
        - front_left_second_joint
        - front_left_third_joint

        # - front_right_first_joint
        # - front_right_second_joint
        # - front_right_third_joint

        # - rear_left_first_joint
        # - rear_left_second_joint
        # - rear_left_third_joint

        # - rear_right_first_joint
        # - rear_right_second_joint
        # - rear_right_third_joint

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu
    frame_id: imu_link
    publish_rate: 100.0




joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0
    

