controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    quadruped_controller:
      type: quadruped_controller/QuadrupedController

effort_controllers:
  ros__parameters:
      joints:
        - front_left_first_joint
        - front_left_second_joint
        - front_left_third_joint

        - front_right_first_joint
        - front_right_second_joint
        - front_right_third_joint

        - rear_left_first_joint
        - rear_left_second_joint
        - rear_left_third_joint

        - rear_right_first_joint
        - rear_right_second_joint
        - rear_right_third_joint

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu
    frame_id: imu_link
    publish_rate: 100.0




joint_state_broadcaster:
  ros__parameters:
    publish_rate: 1000.0
    

quadruped_controller:
    ros__parameters:
      joints:
        - front_left_first_joint
        - front_left_second_joint
        - front_left_third_joint
        - front_right_first_joint
        - front_right_second_joint
        - front_right_third_joint
        - rear_left_first_joint
        - rear_left_second_joint
        - rear_left_third_joint
        - rear_right_first_joint
        - rear_right_second_joint
        - rear_right_third_joint

      command_interface: effort
      state_interfaces:
        - position
        - velocity
        - effort

      kinematics:
        plugin_name: quadbar_kinematics/QuadbarKinematics
        plugin_package: quadbar_kinematics
        base: base_link
        tip: end_effector_link
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
